Name = input("enter your name: ")
username = input("enter your username: ")
password = input("enter your password: ")
email = input("enter your email: ")
identity = input("enter your id: ")
Age = input("enter your age: ")
Address = input("enter you address: ")
MontlyIncome = input("monthly income: ")
Yearlyincome = str(int(MontlyIncome) *12)
print("Hi Mr." + Name)
print("your username is" +username) 
print("your password is" + password)
print("your email is" + email)
print("your identity is" + identity)
print("your age is" + Age)
print("your address" + Address)
print("your monthly income is" + MontlyIncome)
print("your yearlyincome is" + Yearlyincome)
 